### ISSUE TITLE
Unable to perform an IBC transfer from OSMOSIS to COMDEX

### ISSUE THREAD

**Issue by cybertronprime** [ctrl-Felix/mospy#19]
While trying to do a IBC transfer from Osmosis to Comdex with the following code
```
#module ibcTxOsmosisComdex
from osmosis_protobuf.ibc.applications.transfer.v1.tx_pb2 import MsgTransfer
from osmosis_protobuf.cosmos.base.v1beta1.coin_pb2 import Coin
from osmosis_protobuf.ibc.core.client.v1.client_pb2 import Height # Optional, see comments below
import osmosis_protobuf.osmosis.gamm.v1beta1.tx_pb2 as tx_osmosis


from mospy import Transaction, Account
from mospy.clients import HTTPClient



async def ibcOsmosisComdex():

    # Client
    client = HTTPClient(
        api="https://rpc-osmosis.whispernode.com:443"
      
       
    )
   
    account = Account(
        seed_phrase="<seed-phrase>",
        account_number=0,
        next_sequence=0,
        hrp="osmo",
        protobuf="osmosis"

    )
    tx = Transaction(
        account=account,
        chain_id="osmosis-1",
        gas=100000,
        protobuf="osmosis",
        

    )


    timeout_height = Height(
        revision_number=1,
        revision_height=1234
    )
    tmsg = MsgTransfer(
        source_port="transfer",
        source_channel="channel-87",
        token=Coin(amount="100000",denom="uosmo"),
        timeout_height=timeout_height,
        timeout_timestamp=0,
        sender=account.address,
        receiver="comdex1lpdh96n0h6z2h066eqvsh6aykmpc95388s8z3l",
        
        

    )

    tx.set_fee(
        amount=250000,
        denom="uosmo"
    )
    tx.add_raw_msg(tmsg, type_url="/ibc.applications.transfer.v1.MsgTransfer")

    result=client.broadcast_transaction(transaction=tx)
    print(result)
```
```
i get the following error:
Traceback (most recent call last):
  File "/Users/rohitprasad/Library/Python/3.9/lib/python/site-packages/httpcore/_exceptions.py", line 10, in map_exceptions
    yield
  File "/Users/rohitprasad/Library/Python/3.9/lib/python/site-packages/httpcore/backends/sync.py", line 62, in start_tls
    raise exc
  File "/Users/rohitprasad/Library/Python/3.9/lib/python/site-packages/httpcore/backends/sync.py", line 57, in start_tls
    sock = ssl_context.wrap_socket(
  File "/Library/Developer/CommandLineTools/Library/Frameworks/Python3.framework/Versions/3.9/lib/python3.9/ssl.py", line 500, in wrap_socket
    return self.sslsocket_class._create(
  File "/Library/Developer/CommandLineTools/Library/Frameworks/Python3.framework/Versions/3.9/lib/python3.9/ssl.py", line 1040, in _create
    self.do_handshake()
  File "/Library/Developer/CommandLineTools/Library/Frameworks/Python3.framework/Versions/3.9/lib/python3.9/ssl.py", line 1309, in do_handshake
    self._sslobj.do_handshake()
ssl.SSLError: [SSL: TLSV1_ALERT_PROTOCOL_VERSION] tlsv1 alert protocol version (_ssl.c:1129)

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/Users/rohitprasad/Library/Python/3.9/lib/python/site-packages/httpx/_transports/default.py", line 60, in map_httpcore_exceptions
    yield
  File "/Users/rohitprasad/Library/Python/3.9/lib/python/site-packages/httpx/_transports/default.py", line 218, in handle_request
    resp = self._pool.handle_request(req)
  File "/Users/rohitprasad/Library/Python/3.9/lib/python/site-packages/httpcore/_sync/connection_pool.py", line 253, in handle_request
    raise exc
  File "/Users/rohitprasad/Library/Python/3.9/lib/python/site-packages/httpcore/_sync/connection_pool.py", line 237, in handle_request
    response = connection.handle_request(request)
  File "/Users/rohitprasad/Library/Python/3.9/lib/python/site-packages/httpcore/_sync/connection.py", line 86, in handle_request
    raise exc
  File "/Users/rohitprasad/Library/Python/3.9/lib/python/site-packages/httpcore/_sync/connection.py", line 63, in handle_request
    stream = self._connect(request)
  File "/Users/rohitprasad/Library/Python/3.9/lib/python/site-packages/httpcore/_sync/connection.py", line 150, in _connect
    stream = stream.start_tls(**kwargs)
  File "/Users/rohitprasad/Library/Python/3.9/lib/python/site-packages/httpcore/backends/sync.py", line 62, in start_tls
    raise exc
  File "/Library/Developer/CommandLineTools/Library/Frameworks/Python3.framework/Versions/3.9/lib/python3.9/contextlib.py", line 135, in __exit__
    self.gen.throw(type, value, traceback)
  File "/Users/rohitprasad/Library/Python/3.9/lib/python/site-packages/httpcore/_exceptions.py", line 14, in map_exceptions
    raise to_exc(exc)
httpcore.ConnectError: [SSL: TLSV1_ALERT_PROTOCOL_VERSION] tlsv1 alert protocol version (_ssl.c:1129)

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "/Users/rohitprasad/Desktop/PROJECTS/arbBot-v2/main.py", line 92, in <module>
    asyncio.run(main())
  File "/Library/Developer/CommandLineTools/Library/Frameworks/Python3.framework/Versions/3.9/lib/python3.9/asyncio/runners.py", line 44, in run
    return loop.run_until_complete(main)
  File "/Library/Developer/CommandLineTools/Library/Frameworks/Python3.framework/Versions/3.9/lib/python3.9/asyncio/base_events.py", line 642, in run_until_complete
    return future.result()
  File "/Users/rohitprasad/Desktop/PROJECTS/arbBot-v2/main.py", line 85, in main
    await ibcOsmosisComdex()
  File "/Users/rohitprasad/Desktop/PROJECTS/arbBot-v2/ibcTxOsmosisComdex.py", line 63, in ibcOsmosisComdex
    result=client.broadcast_transaction(transaction=tx)
  File "/Users/rohitprasad/Library/Python/3.9/lib/python/site-packages/mospy/clients/HTTPClient.py", line 79, in broadcast_transaction
    data = self._make_post_request(path, payload, timeout)
  File "/Users/rohitprasad/Library/Python/3.9/lib/python/site-packages/mospy/clients/HTTPClient.py", line 22, in _make_post_request
    req = httpx.post(self._api + path, json=payload, timeout=timeout)
  File "/Users/rohitprasad/Library/Python/3.9/lib/python/site-packages/httpx/_api.py", line 304, in post
    return request(
  File "/Users/rohitprasad/Library/Python/3.9/lib/python/site-packages/httpx/_api.py", line 100, in request
    return client.request(
  File "/Users/rohitprasad/Library/Python/3.9/lib/python/site-packages/httpx/_client.py", line 821, in request
    return self.send(request, auth=auth, follow_redirects=follow_redirects)
  File "/Users/rohitprasad/Library/Python/3.9/lib/python/site-packages/httpx/_client.py", line 908, in send
    response = self._send_handling_auth(
  File "/Users/rohitprasad/Library/Python/3.9/lib/python/site-packages/httpx/_client.py", line 936, in _send_handling_auth
    response = self._send_handling_redirects(
  File "/Users/rohitprasad/Library/Python/3.9/lib/python/site-packages/httpx/_client.py", line 973, in _send_handling_redirects
    response = self._send_single_request(request)
  File "/Users/rohitprasad/Library/Python/3.9/lib/python/site-packages/httpx/_client.py", line 1009, in _send_single_request
    response = transport.handle_request(request)
  File "/Users/rohitprasad/Library/Python/3.9/lib/python/site-packages/httpx/_transports/default.py", line 218, in handle_request
    resp = self._pool.handle_request(req)
  File "/Library/Developer/CommandLineTools/Library/Frameworks/Python3.framework/Versions/3.9/lib/python3.9/contextlib.py", line 135, in __exit__
    self.gen.throw(type, value, traceback)
  File "/Users/rohitprasad/Library/Python/3.9/lib/python/site-packages/httpx/_transports/default.py", line 77, in map_httpcore_exceptions
    raise mapped_exc(message) from exc
httpx.ConnectError: [SSL: TLSV1_ALERT_PROTOCOL_VERSION] tlsv1 alert protocol version (_ssl.c:1129)
```

**Comment by ctrl-Felix** [comment]
It seems like you're using an rpc node. However, the HTTPClient has to be instantiated with an api node.

Can you try it again with https://lcd-osmosis.whispernode.com?

**Comment by cybertronprime** [comment]
Tried, same error.
```

python3 main.py
Traceback (most recent call last):
  File "/Users/rohitprasad/Library/Python/3.9/lib/python/site-packages/httpcore/_exceptions.py", line 10, in map_exceptions
    yield
  File "/Users/rohitprasad/Library/Python/3.9/lib/python/site-packages/httpcore/backends/sync.py", line 62, in start_tls
    raise exc
  File "/Users/rohitprasad/Library/Python/3.9/lib/python/site-packages/httpcore/backends/sync.py", line 57, in start_tls
    sock = ssl_context.wrap_socket(
  File "/Library/Developer/CommandLineTools/Library/Frameworks/Python3.framework/Versions/3.9/lib/python3.9/ssl.py", line 500, in wrap_socket
    return self.sslsocket_class._create(
  File "/Library/Developer/CommandLineTools/Library/Frameworks/Python3.framework/Versions/3.9/lib/python3.9/ssl.py", line 1040, in _create
    self.do_handshake()
  File "/Library/Developer/CommandLineTools/Library/Frameworks/Python3.framework/Versions/3.9/lib/python3.9/ssl.py", line 1309, in do_handshake
    self._sslobj.do_handshake()
ssl.SSLError: [SSL: TLSV1_ALERT_PROTOCOL_VERSION] tlsv1 alert protocol version (_ssl.c:1129)

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/Users/rohitprasad/Library/Python/3.9/lib/python/site-packages/httpx/_transports/default.py", line 60, in map_httpcore_exceptions
    yield
  File "/Users/rohitprasad/Library/Python/3.9/lib/python/site-packages/httpx/_transports/default.py", line 218, in handle_request
    resp = self._pool.handle_request(req)
  File "/Users/rohitprasad/Library/Python/3.9/lib/python/site-packages/httpcore/_sync/connection_pool.py", line 253, in handle_request
    raise exc
  File "/Users/rohitprasad/Library/Python/3.9/lib/python/site-packages/httpcore/_sync/connection_pool.py", line 237, in handle_request
    response = connection.handle_request(request)
  File "/Users/rohitprasad/Library/Python/3.9/lib/python/site-packages/httpcore/_sync/connection.py", line 86, in handle_request
    raise exc
  File "/Users/rohitprasad/Library/Python/3.9/lib/python/site-packages/httpcore/_sync/connection.py", line 63, in handle_request
    stream = self._connect(request)
  File "/Users/rohitprasad/Library/Python/3.9/lib/python/site-packages/httpcore/_sync/connection.py", line 150, in _connect
    stream = stream.start_tls(**kwargs)
  File "/Users/rohitprasad/Library/Python/3.9/lib/python/site-packages/httpcore/backends/sync.py", line 62, in start_tls
    raise exc
  File "/Library/Developer/CommandLineTools/Library/Frameworks/Python3.framework/Versions/3.9/lib/python3.9/contextlib.py", line 135, in __exit__
    self.gen.throw(type, value, traceback)
  File "/Users/rohitprasad/Library/Python/3.9/lib/python/site-packages/httpcore/_exceptions.py", line 14, in map_exceptions
    raise to_exc(exc)
httpcore.ConnectError: [SSL: TLSV1_ALERT_PROTOCOL_VERSION] tlsv1 alert protocol version (_ssl.c:1129)

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "/Users/rohitprasad/Desktop/PROJECTS/arbBot-v2/main.py", line 185, in <module>
    asyncio.run(main())
  File "/Library/Developer/CommandLineTools/Library/Frameworks/Python3.framework/Versions/3.9/lib/python3.9/asyncio/runners.py", line 44, in run
    return loop.run_until_complete(main)
  File "/Library/Developer/CommandLineTools/Library/Frameworks/Python3.framework/Versions/3.9/lib/python3.9/asyncio/base_events.py", line 642, in run_until_complete
    return future.result()
  File "/Users/rohitprasad/Desktop/PROJECTS/arbBot-v2/main.py", line 178, in main
    await ibcOsmosisComdex()
  File "/Users/rohitprasad/Desktop/PROJECTS/arbBot-v2/ibcTxOsmosisComdex.py", line 62, in ibcOsmosisComdex
    client.broadcast_transaction(transaction=tx)
  File "/Users/rohitprasad/Library/Python/3.9/lib/python/site-packages/mospy/clients/HTTPClient.py", line 79, in broadcast_transaction
    data = self._make_post_request(path, payload, timeout)
  File "/Users/rohitprasad/Library/Python/3.9/lib/python/site-packages/mospy/clients/HTTPClient.py", line 22, in _make_post_request
    req = httpx.post(self._api + path, json=payload, timeout=timeout)
  File "/Users/rohitprasad/Library/Python/3.9/lib/python/site-packages/httpx/_api.py", line 304, in post
    return request(
  File "/Users/rohitprasad/Library/Python/3.9/lib/python/site-packages/httpx/_api.py", line 100, in request
    return client.request(
  File "/Users/rohitprasad/Library/Python/3.9/lib/python/site-packages/httpx/_client.py", line 821, in request
    return self.send(request, auth=auth, follow_redirects=follow_redirects)
  File "/Users/rohitprasad/Library/Python/3.9/lib/python/site-packages/httpx/_client.py", line 908, in send
    response = self._send_handling_auth(
  File "/Users/rohitprasad/Library/Python/3.9/lib/python/site-packages/httpx/_client.py", line 936, in _send_handling_auth
    response = self._send_handling_redirects(
  File "/Users/rohitprasad/Library/Python/3.9/lib/python/site-packages/httpx/_client.py", line 973, in _send_handling_redirects
    response = self._send_single_request(request)
  File "/Users/rohitprasad/Library/Python/3.9/lib/python/site-packages/httpx/_client.py", line 1009, in _send_single_request
    response = transport.handle_request(request)
  File "/Users/rohitprasad/Library/Python/3.9/lib/python/site-packages/httpx/_transports/default.py", line 218, in handle_request
    resp = self._pool.handle_request(req)
  File "/Library/Developer/CommandLineTools/Library/Frameworks/Python3.framework/Versions/3.9/lib/python3.9/contextlib.py", line 135, in __exit__
    self.gen.throw(type, value, traceback)
  File "/Users/rohitprasad/Library/Python/3.9/lib/python/site-packages/httpx/_transports/default.py", line 77, in map_httpcore_exceptions
    raise mapped_exc(message) from exc
httpx.ConnectError: [SSL: TLSV1_ALERT_PROTOCOL_VERSION] tlsv1 alert protocol version (_ssl.c:1129)
```

**Comment by ctrl-Felix** [comment]
Can you try to make a httpx request to that node in a separate file to see if that works?

And are you using any kind of proxy?

https://github.com/encode/httpx/issues/1434 This is the same error

**Comment by cybertronprime** [comment]
No proxy. just the code i pasted. still fails

**Comment by ctrl-Felix** [comment]
Well, this is definitely not an issue with mospy. The underlying package is httpx. 

I'd either try with another node or submit the tx by yourself without the mospy client.

**Comment by cybertronprime** [comment]
So I was trying to this :
```

from mospy import Account, Transaction
from osmosis_protobuf.osmosis.gamm.v1beta1.tx_pb2 import MsgSwapExactAmountIn
import osmosis_protobuf.osmosis.poolmanager.v1beta1.swap_route_pb2 as tx_osmosis
from mospy.clients import HTTPClient
import mospy
from comdexpy.proto.cosmos.base.v1beta1 import Coin
import httpx
import json

seed_phrase = ""

account = Account(
    seed_phrase=seed_phrase,
    account_number=630264,
    next_sequence=0,
    hrp="osmo",
    protobuf="osmosis"
)
client = HTTPClient(api="https://grpc.osmosis.zone")

tx = Transaction( account=account, chain_id="osmosis-1", gas=1000, protobuf="osmosis")

msg = MsgSwapExactAmountIn()
msg.sender = account.address

routes = [
    {'pool_id': "600", 'denom': "uosmo"},
]
for route in routes:
    _route = tx_osmosis.SwapAmountInRoute()
    _route.pool_id = int(route["pool_id"])
    _route.token_out_denom = route["denom"]
    msg.routes.append(_route)


msg.token_in.denom = "ibc/EA3E1640F9B1532AB129A571203A0B9F789A7F14BB66E350DCBFA18E1A1931F0"
msg.token_in.amount = str(1000)
msg.token_out_min_amount = str(1000)

tx.add_raw_msg(msg, type_url="/osmosis.gamm.v1beta1.MsgSwapExactAmountIn")
tx.set_fee( amount=25000, denom="uosmo")


try:
    client.broadcast_transaction(transaction=tx)
except mospy.exceptions.clients.NodeException as e:
    print(f"Error while broadcasting transaction: {e}")
# print(client.broadcast_transaction(transaction=tx))

# Sign and encode transaction to submit it to the network manually

# REST endpoint (RPC or API)
# tx_bytes = tx.get_tx_bytes_as_string()

# # Submit the transaction through the Tendermint RPC
# rpc_url = "https://rpc.osmosis.zone/"
# pushable_tx = json.dumps(
#               {
#                 "jsonrpc": "2.0",
#                 "id": 1,
#                 "method": "broadcast_tx_sync", # Available methods: broadcast_tx_sync, broadcast_tx_async, broadcast_tx_commit
#                 "params": {
#                     "tx": tx_bytes
#                 }
#               }
#             )
# r = httpx.post(rpc_url, data=pushable_tx)
# print(r)

# Submit the transaction through the Cosmos REST API
# rpc_api = "https://osmosis-rpc.polkachu.com/cosmos/tx/v1beta1/txs"
# pushable_tx = json.dumps(
#                 {
#                   "tx_bytes": tx_bytes,
#                   "mode": "BROADCAST_MODE_SYNC" # Available modes: BROADCAST_MODE_SYNC, BROADCAST_MODE_ASYNC, BROADCAST_MODE_BLOCK
#                 }
#               )
# r = httpx.post(rpc_api, data=pushable_tx)
# print(r)
```
And I got this error:
```
Traceback (most recent call last):
  File "/Users/rohitprasad/Desktop/PROJECTS/arbBot-v2/swapTxOsmosis.py", line 49, in <module>
    print(client.broadcast_transaction(transaction=tx))
  File "/Users/rohitprasad/Library/Python/3.9/lib/python/site-packages/mospy/clients/HTTPClient.py", line 80, in broadcast_transaction
    data = self._make_post_request(path, payload, timeout)
  File "/Users/rohitprasad/Library/Python/3.9/lib/python/site-packages/mospy/clients/HTTPClient.py", line 31, in _make_post_request
    raise NodeException(f"Error while doing request to api endpoint {message}")
mospy.exceptions.clients.NodeException: Error while doing request to api endpoint 

```
I just want to see a working example for maybe an IBC tx or a swap on osmosis. But i am unable to see anything work .

**Comment by ctrl-Felix** [comment]
The HTTP client won't work with GRPC. 

Either use the GRPCClient or use a api endpoint.

Check out https://cosmos.directory/osmosis to find an api

**Comment by cybertronprime** [comment]
Just one more question. Suppose Comdex does not have ibc integrated in their python sdk. Is there a way to still do a comdex to osmosis IBC  programtically?

**Comment by ctrl-Felix** [comment]
Yes, it should work the like sending it to any other chain to be honest. The issue you are having there is more a node issue than a chain issue.

You can use cosmospy protobuf for Comdex too because the standard tx types are usually all the same. You won't have comdex native transactions but for doing an IBC transfer it should work out.

**Comment by ctrl-Felix** [comment]
Closing this issue now. If there's still an issue let me know
